apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessmodes:
    - "ReadWriteOnce"
  storageClassName: mongo-ebs    
  resources:
    requests:
      storage: 5Gi

--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclainPolicy: Delete    
